[package]
name = "rust-test-rocket-server"
version = "0.1.0"
authors = ["Alexander Zenov <alexander.zenov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.4.5", default-features = false }
rocket_cors = { version = "0.5.2", default-features = false }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
rust-crypto = "0.2.36"
chrono = { version = "0.4.15", features = ["serde"] }
diesel = { version = "1.4.5", features = ["postgres", "chrono"] }
validator = "0.10.1"
validator_derive = "0.10.1"
slug = "0.1.4"
rand = "0.7.3"
dotenv = "0.15.0"
jsonwebtoken = "7.2.0"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json", "diesel_postgres_pool"]

[dev-dependencies]
once_cell = "1.4.0"

[features]
default = ["random-suffix"]

# Enable generation of random suffix when making article slug. This
# allows having multiple articles with the same title.
random-suffix = []